### PR TITLE
Fixed error crashing BCL when github is down and ask to update

### LINKED ISSUE #283: [BUG REPORT]  BCL doesn't work when github is down
### Pre-Flight Checklist

- [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
- [X] I have tried to use an [alternative voice server](https://bettercrewl.ink/)
- [X] I have checked everyone in my lobby is on the same BetterCrewLink/CrewLink server
- [X] I have refreshed and activated <kbd>NAT Fix</kbd> on the BetterCrewLink app when I can't hear some people (this is a known issue)
- [X] I have checked that the BetterCrewLink/CrewLink server I'm using is up to date
- [X] I have a screenshot or videos of any errors
- [X] I have checked that someone else has not reported this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)

### Describe the bug

BCL stops working when github goes down (because of updater)

### Steps to reproduce the behavior

xxx

### Expected behavior

It should load and not crach xD

### Screenshots/Videos

_No response_

### Desktop

- OS: [e.g. Windows 11]
- Version: all

### Additional context

xx

### PR DESCRIPTION
**Pull request by JKohlman**
Mostly closes #283, still has issue with offsets from github not working if github is down.

To simulate Github being down:
Edit `C:\Windows\System32\drivers\etc\hosts` to include `127.0.0.1 github.com` and run `ipconfig /flushdns`
To undo:
Remove `127.0.0.1 github.com` from hosts file, run `ipconfig /flushdns`

### CODE REVIEW

File: src/main/index.ts [hunk 1]
```diff
@@ -224,11 +224,13 @@ const gotTheLock = app.requestSingleInstanceLock();
 if (!gotTheLock) {
 	app.quit();
 } else {
+	autoUpdater.autoDownload = false;
```
Comment (OhMyGuus) [inline src/main/index.ts:227]: lol

**Comment by OhMyGuus** [comment]
Amazing job :)
